### ISSUE TITLE
long int as key

### ISSUE THREAD

**Issue by lourenko** [troydhanson/uthash#105]
I would like to know if there is any possibility to use a `long int` or `long long int` as a key in uthash. I made some tests using keys like 4498690746, but when I retrieve the value, it is 203723450. Thanks in advance.

**Comment by Quuxplusone** [comment]
Yes, keys of non-`int` types work fine. You've got a bug in your code somewhere; my guess is that you're passing the 64-bit value through a function you've written that takes an `int` parameter, so that its high-order bits are getting stripped off.
Alternatively, you might be "retrieving" the value in the wrong way.
Alternatively, you might be thinking that `long` has 64 bits when you're actually programming on a platform where `long` is 32-bit, in which case changing the word `long` to `long long` (or even better, `int64_t`) would fix your bug.

For help debugging your code, I recommend asking on http://stackoverflow.com/questions/tagged/uthash rather than on this GitHub project; you'll get a wider audience. Anyway, you'll have to show the code in question in order for anyone to help debug it.
