### ISSUE TITLE
Stable versions of uthash?

### ISSUE THREAD

**Issue by ijustlovemath** [troydhanson/uthash#116]
I'm an embedded developer on a university satellite project, and plan to fly uthash as part of our core data structures library. We're currently using 2.0.1 and have not had any issues, but I was wondering if there were "stable" versions beyond just what we find here on GitHub. Sort of like how Ubuntu has LTS and normal releases, I'm trying to see if this library has an LTS version. No need for guarantees or support, just stability.

**Comment by Quuxplusone** [comment]
Hi @ijustlovemath! If you're looking for long-term stability, I recommend just vendoring the `uthash.h` header file into your own repository. It's a single-file header-only library, so that's really easy; and then it's as stable as it's possible to be. :)

I think the thing that you get with Ubuntu LTS releases is a "release branch", i.e. a branch that receives *some* patches (e.g. security patches) but not *all* patches (e.g. new features). uthash has nothing like that.
