### ISSUE TITLE
Number of calls to uthash_strlen

### ISSUE THREAD

**Issue by tbeu** [troydhanson/uthash#131]
The convenience macros HASH_FIND_STR, HASH_ADD_STR and HASH_REPLACE_STR call uthash_strlen more frequently than necessary. I would recommend to cache this key length and pass it to HASH_FIND, HASH_ADD and HASH_REPLACE, respectively.

**Comment by Quuxplusone** [comment]
Hmm. That's true, but isn't there a slippery slope here, given that *every* macro in uthash.h evaluates its arguments multiple times? In the general case, we ought to pull out *every* macro argument into a local variable, e.g.

    #define HASH_VALUE(keyptr,keylen,hashv)                                          \
    do {                                                                             \
      HASH_FCN(keyptr, keylen, hashv);                                               \
    } while (0)

arguably ought to be

    #define HASH_VALUE(keyptr,keylen,hashv)                                          \
    do {                                                                             \
      const void *_hv_keyptr = (const void *)(keyptr);                               \
      unsigned _hv_keylen = (keylen);                                                \
      unsigned *_hv_hashv = &(hashv);                                                \
      HASH_FCN(_hv_keyptr, _hv_keylen, *_hv_hashv);                                  \
    } while (0)

in order to avoid pessimizing user code like `HASH_VALUE(message(i), strlen(message(i)), hasharr[i % hasharr_size()])`. At a certain point we *have* to say "okay, the user should just rewrite their code to use a local variable themselves; they know this stuff is all macros." The question is just *where is that point?*

Arguably the difference here is that it's *possible* for user code to use `HASH_VALUE` efficiently by judicious use of local variables in user code; but it is currently *not possible* to use `HASH_ADD_STR` efficiently at all. So `HASH_ADD_STR` merits fixing and `HASH_VALUE` doesn't. What's your take on the situation?

**Comment by tbeu** [comment]
I definitely would not touch macros like HASH_VALUE as long as the user has the chance to use local variables in his/her own code when calling the macro. However, it is impossible to do so when calling convenience macros like HASH_FIND_STR, HASH_ADD_STR and HASH_REPLACE_STR. Thus, I'd update only the necessary ones.

**Comment by tbeu** [comment]
PVS-Studio reports:
* V814 Decreased performance. The 'strlen' function was called multiple times inside the body of a loop.

**Comment by tbeu** [comment]
Any chance? PR welcome?

**Comment by Quuxplusone** [comment]
PR welcome.
