### ISSUE TITLE
New APIs to create hash table with user defined size before operating hash table.

### ISSUE THREAD

**Issue by jjhuo** [troydhanson/uthash#148]
Right now, uthash will allocate memory during first insertion, and default bucket number is only 8. For some advanced users, we want to avoid memory allocation happening at all during entry insertion, and we can achieve this by creating the hash table with user defined bucket numbers.

C++ hash table has function call (std::unordered_map::reserve) to do this. Uthash can do similar things.
1. Make HASH_MAKE_TABLE() an API 
2. add new reserve() API to pass HASH_INITIAL_NUM_BUCKETS from user.

This feature will be very useful, please kindly consider to implement it.

**Comment by Quuxplusone** [comment]
Hi @jjhuo! I like this idea in principle, but I don't immediately see how to implement it, for two reasons. Let's assume for the sake of argument that the interface would be like this:

    myelement_t *myhash = NULL;
    HASH_RESERVE(myhash, 100);  // reserve 100 buckets

1. Right now, uthash has the invariant that an empty hashtable is a null pointer. If you were allowed to call `HASH_RESERVE` as above, you'd create a hashtable that was somehow "still empty, but with buckets." The physical pointer `myhash` can't be null at this point, because we have to track the buckets *somehow*. If it's not null, it must point to an object of type `myelement_t`, by definition. So where does this `myelement_t` object come from? uthash doesn't know how to create objects of that type!

2. Right now, uthash has the invariant that the number of buckets (if any) is always a power of 2. Not only that, but uthash stores the *log2* of the number of buckets internally! This is why the header defines both `HASH_INITIAL_NUM_BUCKETS` *and* `HASH_INITIAL_NUM_BUCKETS_LOG2`. This in turn means that these two macros must stay perfectly in sync, which means that just doing

        #undef HASH_INITIAL_NUM_BUCKETS
        #define HASH_INITIAL_NUM_BUCKETS 256

    in your own code will *not* do the right thing (it will probably crash) because you didn't simultaneously change `HASH_INITIAL_NUM_BUCKETS_LOG2` to `8`. And *that* fragility explains why neither of these macros is documented as a customization point for the user (unlike, say, `uthash_malloc`).

    So allowing `HASH_RESERVE(myhash, 100)` would break the invariant that the number of buckets was always a power of two. (Of course we could assert-fail, or round up the number of buckets in that case.)

    But then a related problem: once we've converted the user-supplied number of buckets to a power of 2, how do we compute the log2 of that number, in a macro-friendly way? I mean there *are* ways I can think of (use a compiler builtin, use a loop), but none of them are particularly nice.

So because of all these issues, I am not personally inclined to look into this issue any further. If you can come up with a proposed patch, or solve some of these issues cleanly, then I certainly might be persuaded to revisit it. I'll leave the issue open for now.

**Comment by jjhuo** [comment]
My usage is going to be, starting from a few items in the hash table, and then growing to more than 200K items in the hash table. Uthash will rehash a lot of times during this usage model, and my application is very very latency sensitive. All advanced hash tables have this feature to reserve a predefined number of entries to avoid costly rehashing.

1. Maybe it's good time to restructure uthash, in order to provide more features. Then more people, like me, can consider to use it in productions.
2. We can let user pass log2 of bucket number.

**Comment by Quuxplusone** [comment]
1. You are welcome to fork uthash in order to make it more "advanced". I suspect that what you'll end up with, though, is an thin C wrapper around an "advanced" hash table that doesn't look anything like uthash either in implementation or in interface. (It'd probably be based on inline functions or templates rather than macros, for example.) Have you looked into other hashtable implementations such as `unordered_map`, `boost::unordered_map`, [Google `dense_hash_map`](https://github.com/sparsehash/sparsehash), [`ska::flat_hash_map`](https://probablydance.com/2017/02/26/i-wrote-the-fastest-hashtable/), etc?

2. Yes, that's true; `HASH_RESERVE_2N(myhash, 7)` could mean "reserve 128 buckets."

Have you tried just setting these macros in your own code? Do you actually observe the speedup you expect?

Have you computed how many extra mallocs you're paying for in the worst case (say, 200M elements in the table — what's log2 of 200,000,000?) and multiplied that by the cost in milliseconds of a single malloc?

**Comment by jjhuo** [comment]
1. thanks for the links, yes, I have looked into them before. I have to use C version hashtable, that's why I couldn't use them.

In the worse case, I have seen, in servers running for long time, malloc caused many seconds delay. The idea is to avoid malloc and rehash to happen as less as possible.
