### ISSUE TITLE
HASH_FIND_XXX Warning C4127 conditional expression is constant

### ISSUE THREAD

**Issue by GF-Huang** [troydhanson/uthash#181]
`HASH_FIND_XXX` cause `Warning C4127 conditional expression is constant`
and
`HASH_ADD_XXX` cause `warning C4702: unreachable code for one exception handling`

**Comment by Jeff17Robbins** [comment]
Adding more context, in case this helps us resolve this issue.

`HASH_FIND_BYHASHVALUE`, for example, has this line in it:

**Comment by Quuxplusone** [comment]
Thanks for the information; that's useful!

Indeed, MSVC seems to warn about `if (1 != 0)` but not about `if (1)`, even though they mean the same thing. So if this was all there was to it, I'd say let's just eliminate the redundant `!= 0` and be done.

Unfortunately, `git blame` informs me that the redundant `!= 0` was *added* in commit 15d56535f01e85482493cbf0140834f2f78eb382 by @fperrad, with the goal of making this code MISRA-clean(er). #69 has similarities to this issue:

- no functional change

- eliminate a compiler warning on submitter's compiler of choice

- submitter's compiler of choice is *unusual* in emitting this warning; [competing compilers don't complain about the code as written](https://godbolt.org/z/zt56Wc)

I don't think it's productive to churn the code back and forth (see: [edit war](https://en.wikipedia.org/wiki/Wikipedia:Lamest_edit_wars)) in order to satisfy unusual compilers' dietary restrictions. *Especially* because there is no way to test the result. Ideally, every PR would come with a new regression test. But if that regression test depends on the behavior of a non-free third-party tool, we can't hook it up to CI, and so the behavior with respect to that tool *will* regress over time. Besides, the next version of the non-free tool might fix the warning itself.

So at least in the case of `!= 0`, I think the right thing to do is leave the code un-churned. MSVC users can compile with `-wd4127` and/or add some pragmas to their codebase.

**Comment by Jeff17Robbins** [comment]
That's fair -- I agree.
