### ISSUE TITLE
Please add the library.properties file to use this library in Arduino without error

### ISSUE THREAD

**Issue by VoLinhTruc** [troydhanson/uthash#220]
Originally, after clone this library to Arduino library directory, I met error at the first build (as shown in the first image below)
After discovering, I see that to solve this error, library.properties is need. Blank file can also solve the error (as shown in the second image below).

So please add this file to project.

![image](https://user-images.githubusercontent.com/26188668/103560338-32692f00-4eea-11eb-9bd8-53b9bc0b3dcd.png)

![image](https://user-images.githubusercontent.com/26188668/103560485-6c3a3580-4eea-11eb-8dc8-0b56d8ad8012.png)

**Comment by Quuxplusone** [comment]
I may not understand the issue here, but this vaguely reminds me of #84 — basically you're saying "this isn't packaged quite right for my specific distribution," and then wanting to modify uthash itself (albeit very minorly) so that it'll become acceptable to your particular distribution. Contrariwise, *I* would like to keep a strong firewall between "the troydhanson/uthash source repo itself" and "how it's packaged by some distributor" (e.g. Homebrew, Debian, Ubuntu, etc).
I don't want this GitHub repo to get into the business of maintaining a _distribution format_; I want to provide just a _single .h file_ which distro maintainers can take and package appropriately for their own distros if that's what they want to do.

Casual users of the top-of-tree "uthash.h" should probably just `cp` the file directly into their source directory.

Anyway, in your specific case, it sounds like you currently have a build script that does something like

    git clone https://github.com/troydhanson/uthash uthash

and you should just change your build script to do

    git clone https://github.com/troydhanson/uthash uthash
    touch uthash/library.properties

instead. That should work fine, right? And more importantly to me, when that solution breaks, maybe five years from now, it'll be _your_ problem and not mine. ;)
