### ISSUE TITLE
"UT_hash_table" is reserved, shoud be mentioned in document

### ISSUE THREAD

**Issue by daihuichen** [troydhanson/uthash#240]
It is very natural to write code like 
`struct my_struct* UT_hash_table = NULL;`
but "UT_hash_table" is reserved in uthash, and an compiling error will occur.
It took me a while to discover the reason, so better to mentioned in the document.

**Comment by Quuxplusone** [comment]
I'm not sure `UT_hash_table` is a very "natural" name for a variable in C — I'd think `h` or `hh`, or something that actually describes the purpose of the variable, such as `users` or `events` or `books_by_isbn`. But sure, if you suggest a documentation patch, I'll probably accept it. (As is, I'm not sure where in the documentation someone would look and expect to find that piece of information.)

`struct UT_hash_bucket` is also defined in uthash.h.

Preemptive note: One might think we could just _change the names_ of these three struct types to push them more into clearly-reserved-to-the-library territory (e.g. prefix them with `HASH_` instead of `UT_`); but that would affect name mangling in C++, so I'd push back very hard on that idea.

**Comment by daihuichen** [comment]
Great, maybe you can mention it where you define a UT hash table for the first time in the document~ 
And yes, after finding `UT_hash_table` is defined, I looked into the code and found `struct UT_hash_bucket` is also defined.
