### ISSUE TITLE
Is ID really needed?

### ISSUE THREAD

**Issue by ms-gx** [troydhanson/uthash#244]
I am using uthash to have a "hashed" set. So I do not need a key-value pair but I only need to know if the set contains a specific value. 

My struct is:
```
struct hash_struct {
    char name[42];
    int id;
    UT_hash_handle hh;         /* makes this structure hashable */
};
```

I am feeding and querying `name` to/from the hashtable via `HASH_ADD_STR` and `HASH_FIND_STR`. Can I just omit `int id`? My hope is to save a bit on storage and speed, even if not much.

So the id  I am providing is just a pseudo-count and not needed for my functionality.

**Comment by Quuxplusone** [comment]
The only member required by uthash's internals is `UT_hash_handle hh`. (And even the name `hh` is configurable, e.g. by using `HASH_ADD` instead of `HASH_ADD_STR`.) There's nothing magic about `id`. See for example [this sample code](https://troydhanson.github.io/uthash/userguide.html#_pointer_keys), where `el_t` doesn't have an `id` field, and that's fine.

However, FYI, notice that on a 64-bit platform the layout of your `hash_struct` as written will be (42 bytes of chars) + (2 bytes of padding) + (4 bytes of int) + (8 bytes of pointer) for a total of 56 bytes. Removing the `id` field will give you (42 bytes of chars) + (6 bytes of padding) + (8 bytes of pointer) for the same total of 56 bytes. So if you're really trying to improve `sizeof(hash_struct)`, you should (1) study layout and alignment requirements for your platform(s), and (2) measure, measure, measure!
