### ISSUE TITLE
Quick membership check?

### ISSUE THREAD

**Issue by gszol** [troydhanson/uthash#253]
Hi,

Is there maybe a better way to verify membership of an element in a hash than HASH_FINDing it by key?
Perhaps by comparing the hh.tbl pointers?

Thanks in advance, and thank you for the awesome library either way :-)

**Comment by Quuxplusone** [comment]
Short answer "yes", but technically no.

It is true[*] that *if* a node `elt` is in a hashtable `head`, *then* `elt->hh.tbl == head->hh.tbl`. (In that case, `head` must be non-null because `elt` is in it, so it must be non-empty.)
This means that *if* node `e1` is known to be in some hashtable, and node `e2` is also known to be in some hashtable, and `e1->hh.tbl == e2->hh.tbl`, *then* `e1` and `e2` must necessarily be in the _same_ hashtable together.

The reverse is not true: obviously `elt->hh.tbl == head->hh.tbl` can be true for an `elt` that isn't in any hash table at all, because anyone can just _set_ `elt->hh.tbl` to that pointer value. I mean, it's not like there's any class invariant for a node that _isn't_ being managed by a hashtable!

The typical use-case for uthash is when you have a copy of the _data_ of a node (maybe you just received that data from the end-user), and you want to know whether another copy of that data appears anywhere in the hashtable. IMHO it is rare that you actually have a _pointer directly to the node you care about,_ and yet somehow you have forgotten whether that node is in the hashtable or not.

[*] — I _think_ this is true, anyway. I ran a quick test by adding some `assert`s into `uthash.h` and running all the unit tests; the invariant was true everywhere that I checked it.

**Comment by gszol** [comment]
Oh, I didn't think about copies because we never do that in my use case.
We also never directly touch the hash handle structure outside the uthash macros.
So from my perspective as a user, anything the macros do consistently with the hash handle is an upheld invariant.

With that in mind I tried to find where HASH_DELETE and HASH_CLEAR would invalidate hh.tbl on the removed element(s), and it looks like they don't. I guess I should have checked that before asking, sorry.
 
The way it comes up is when an element can be present in multiple hashes by different keys (or other containers), and needs to be removed from all of them after being found in one.

It's purely a coding aesthetics question, I doubt it has any performance impact. I'll just try to think of the check as cache warm-up for the delete :-)

**Comment by Quuxplusone** [comment]
> The way it comes up is when an element can be present in multiple hashes by different keys (or other containers), and needs to be removed from all of them after being found in one.

Ah, that makes sense!

> where HASH_DELETE and HASH_CLEAR would invalidate hh.tbl [...] I'll just try to think of the check as cache warm-up for the delete

Well, HASH_DELETE and HASH_CLEAR assume that the nodes being taken out of the hash are almost certainly going straight to `free`, so it would be a waste of cycles to change their data. But in your own code, you could certainly find the lines that call `HASH_DELETE` and `HASH_CLEAR` and simply add a line afterward to set `node->hh.tbl = NULL`, so that in _your own_ code you could rely on that as an invariant.
