### ISSUE TITLE
warning: shared-lib-calls-exit in uthash 

### ISSUE THREAD

**Issue by kwizart** [troydhanson/uthash#92]
There are few issues with libglvnd (using uthash) package as reported by rpmlint.

```
libglvnd.armv7hl: W: shared-lib-calls-exit /usr/lib/libGLX.so.0.0.0 exit@GLIBC_2.4
libglvnd.i686: W: shared-lib-calls-exit /usr/lib/libGLX.so.0.0.0 exit@GLIBC_2.0
libglvnd.x86_64: W: shared-lib-calls-exit /usr/lib64/libGLX.so.0.0.0 exit@GLIBC_2.2.5
```

This is caused by the (bundled) utash library that handle fatal errors such as:
`#define uthash_fatal(msg) exit(-1)        /* fatal error (out of memory,etc) */`

rpmlint notice about shared-lib-calls-exit:

> This library package calls exit() or _exit(), probably in a non-fork()
> context. Doing so from a library is strongly discouraged - when a library
> function calls exit(), it prevents the calling program from handling the
> error, reporting it to the user, closing files properly, and cleaning up any
> state that the program has. It is preferred for the library to return an
> actual error code and let the calling program decide how to handle the
> situation.

Is this notice relevant for uthash ?
Is there a way to improve error handling here?

Thx

**Comment by tbeu** [comment]
You can define uthash_fatal before you include uthash.h. See https://github.com/tbeu/ModelicaStandardTables/blob/master/C-Sources/ModelicaStandardTables.c#L126-L127 for an example. The `break` works as the macros are defined by do ... while.

**Comment by kwizart** [comment]
Thx, I will try to implement the same for libglvnd.
https://github.com/NVIDIA/libglvnd/issues/106
Closing as there is a way to avoid using exit in uthash.

**Comment by Quuxplusone** [comment]
@tbeu: FWIW, I just took a look at whether I should add a unit-test to uthash to ensure that the idiom in https://github.com/tbeu/ModelicaStandardTables/blob/master/C-Sources/ModelicaStandardTables.c#L126-L127 doesn't get broken accidentally... but I think that idiom has already been broken for a long time. The `break` inside your `uthash_fatal` kicks the control flow out of `HASH_BLOOM_MAKE`, but then the control flow continues steamrolling through the last line of `HASH_MAKE_TABLE`, and then the last six lines of `HASH_ADD_KEYPTR_BYHASHVALUE_INORDER` (including the part that increments `num_items`), and then the tails of whatever other macros are there.

And this has been true since the initial commit 07bca4ce, modulo `HASH_ADD_KEYPTR_BYHASHVALUE_INORDER`'s formerly being known as `HASH_ADD_KEYPTR` (so there were a couple fewer "whatever other macros"), so it didn't just get broken recently, either.

I do think you could get away with a `goto` inside your `uthash_fatal`, but trying to make it work with `break` or `continue` is just asking for trouble.

**Comment by tbeu** [comment]
Oops, that is bad news actually. Thanks for checking it in detail.

**Comment by tbeu** [comment]
I could also call all uthash macros inside functions and have define uthash_fatal as return.

**Comment by tbeu** [comment]
I also reported it as a [ticket](https://trac.modelica.org/Modelica/ticket/2097) on the Modelica Standard Library.

@Quuxplusone @kwizart Can you pls reopen the issue until we found a proper solution.

**Comment by tbeu** [comment]
![goto](http://i.stack.imgur.com/XnPXh.png)

**Comment by troydhanson** [comment]
Yeah, its a wort in uthash - sorry. Would have been better if I returned an error, but of course macros don't "return" anything. I think the warning is good advice particularly in a library. Short of refactoring it seems like goto/abort/longjmp/exit are the options.

**Comment by tbeu** [comment]
Luckily, in my cases, uthash_fatal is only called once from HASH_ADD_KEYPTR in one single function of my libraries. Thus I could leave that function in case of uthash_fatal with a function specific return. But I decided to error out (by ModelicaError functions), which is application dependent for the library user, but basically is longjmp.

**Comment by Quuxplusone** [comment]
I think @kwizart's original closing of this ticket was correct, given that indeed "there is a way to avoid using exit in uthash."  I don't think there's anything uthash could do to make it *easier* to not-use-`exit`; but if there is, wouldn't the ticket at least have to be phrased as "problem X exists with the current `uthash_fatal` interface — person Y tried to use it in project Z and it didn't work for them because X"?  Right now it sounds like the state of the world is

- @kwizart has not been using `uthash_fatal` in libglvnd but should: NVIDIA/libglvnd#106
- @tbeu has been misusing `uthash_fatal` in the Modelica Standard Library: https://trac.modelica.org/Modelica/ticket/2097

but there's no action item here to make any particular change to uthash... unless @troydhanson has something in mind (which I'm counting as a possibility, from the phrase "Short of refactoring..." above).

@tbeu, I left a comment on https://trac.modelica.org/Modelica/ticket/2097 about an alternative approach to using `uthash_fatal`, but your patch's way certainly works too.

**Comment by Quuxplusone** [comment]
@tbeu: Bah, I wrote a big long response on https://trac.modelica.org/Modelica/ticket/2097 and then the spam filter rejected it. Long story short, watch #93 for updates on the definedness of your approach. I now think Modelica should simply `abort()` on malloc failure instead of trying to be clever with control flow.

Either way, I'd strongly prefer if you credited yourself in the Modelica changelog, instead of me, to avoid people thinking they should contact me about Modelica issues just because my name appears high up in the changelog. Thanks!

**Comment by troydhanson** [comment]
Should abort() be the default definition of uthash_fatal?

**Comment by Quuxplusone** [comment]
> Should abort() be the default definition of uthash_fatal?

I lean toward "no".

It sounds like making it `abort()` by default would silence rpmlint errors in a whole bunch of packages; but I doubt that silencing those rpmlint errors should be a goal in itself. Package maintainers might prefer a workflow of "rpmlint complains; investigate; determine what to do if malloc fails in my case" to the alternative workflow of "rpmlint is happy; secretly have references to `abort` in my program."

The fiddliness of rpmlint also gives me pause; what if next month they add a check for "shared-lib-calls-abort"? [The original Bugzilla feature request for shared-lib-calls-exit](https://bugzilla.redhat.com/show_bug.cgi?id=450011) doesn't say anything about `abort` being acceptable; it just lists `exit` and `_exit` as being *un*acceptable because

> when a library function calls exit(), it prevents the calling program from handling the error, reporting it to the user, closing files properly, and cleaning up any state that the program has. It is preferred for the library to return an actual error code and let the calling program decide how to handle the situation.

The same arguments would seem to apply against `abort` as well.

MSDN docs on `abort`: https://msdn.microsoft.com/en-us/library/k089yyh0.aspx
Linux manpage on `abort`: https://linux.die.net/man/3/abort
rpmlint errors on `exit` or `_exit` except in the presence of `fork`: https://github.com/rpm-software-management/rpmlint/blob/f806737641d355389f412f7b84b8a13eb1fb07ff/BinariesCheck.py#L51

**Comment by tbeu** [comment]
Sure, will change the changelog. Yes, the spam rejection is dead annoying. Sorry for that.

**Comment by troydhanson** [comment]
I agree the same argument about rpmlint applies to abort. Apart from rpmlint, there is still at least a minor case to be made for abort. It terminates with signal. It is solely for abnormal exits. If anyone is watching logs it sticks out like a slightly sorer thumb than an exit -1. That said if it were up to me I'd leave it as exit for the unchanginess.

**Comment by tbeu** [comment]
> @tbeu: Bah, I wrote a big long response on https://trac.modelica.org/Modelica/ticket/2097 and then the spam filter rejected it.

@sjoelund Can you do something about the spam filter on the Modelica Trac?

**Comment by sjoelund** [comment]
@tbeu: Not really. The free captcha filters for Trac are no longer working on Debian old-old-old-stable and the Bayesian filter rated the post at 95.45% likelyhood of being spam (although I don't know why it would rate that post as higher spam probability than the designer watches / handbags / shoes that usually spams modelica.org ...).

**Comment by tbeu** [comment]
@sjoelund Can you release that post from spam?

**Comment by sjoelund** [comment]
I can't. This version of trac requires to delete posts to mark them as ham to train the filter.

**Comment by tbeu** [comment]
But can you copy that post content and add it (under your name)?

**Comment by sjoelund** [comment]
No. It's been deleted as ham already.

**Comment by sjoelund** [comment]
Never mind. It seems I had a tab open with the text. Finally, having 100 chrome tabs pays off...

**Comment by tbeu** [comment]
Thanks. Did not know that you are also a tab collector like me.
